---
title: "From 2x2 to GxT DID"
subtitle: "Advances, Problems and Solutions"
author: Fernando Rios-Avila
institute: "Levy Economics Institute of Bard College"
date: "2021-10-13"
format: 
    revealjs: 
        slide-number: true
        width: 1700
        height: 900
        code-fold: true
        code-overflow: wrap
        echo: true
        css: styles.css 
bibliography: did_reg.bib        
nocite: | 
  @*
---

## Why differences in diffences?

- The Differences-in-Differences (DID) model is one of the most commonly used tools in applied economics for analyzing causal effects of an intervention or policy treatment.
- Under reasonable assumptions, DID allows you to identify these effects by comparing changes in the treatment group with changes in the control group.
    - This method of identification even allows for controlling for self-selection in the treatment.
- In recent years, several advances in DID have been developed, revealing issues with the traditional DID design, particularly with the application of TWFE.
- In this course, I will briefly present the problems and solutions that have been proposed, and how they are implemented in `Stata`.

- So lets Start with the basics: 2x2 DID

## 2x2 DID: Cannonic Design

- In the 2x2 DID design, we have 2 groups:
  - Control ($D=1$) y treated ($D=0$), 
- Which are observed for two periods of time:
  - Before ($T=0$) and after ($T=1$) the treatment.
- For all groups and periods of time, we observe the *realized* outcome $Y$, but cannot observe the *potential* outcome.
- This setup is valid both for panel data and repeat cross-sections, but will focus on panel data.
   
## Potential outcomes and Treatment Effects

- **Potential outcomes** are the outcomes we would observe for each observation in the data if it were assigned to either the treatement or control group. 
  - $Y_{i,t}(D=0)$: Potential outcome for individual $i$ at time $t$ if he was never treated.
  - $Y_{j,s}(D=1)$: Potential outcome for individual $j$ at time $s$ if he was treated.
- However, we are only able to observe one of this outcomes:
$$Y_{i,t} = Y_{i,t}(1)D_i + Y_{i,t}(0)(1-D_i)$$

- Where $D_i$ is a dummy indicates the effective treatment status of individual $i$.

- Now, we are interested in Treatment Effects for $i$, or any summary measures, after the treatment is applied:

$$TE = Y_{i,1}(1)-Y_{i,1}(0) \text{ or } ATT =E(Y_{i,1}(1)-Y_{i,1}(0)|D=1)$$


## The DID Estimator: Assumptions

- Because we cant observe both potential outcomes, we need to make assumptions to identify the treatment effect.
  
1. **Stable Unit Treatment Value Assumption (SUTVA)**: The treatment status of one unit does not affect the potential outcomes of other units. (No spillovers)

2. **Parallel Trends**: In the absence of treatment, in average, both groups would have followed the same trend (changes) over time.

$$\color{blue}{E(Y_{i,1}(0) - Y_{i,0}(0)|D_i=1)} = \color{green}{E(Y_{i,1}(0)-Y_{i,0}(0)|D_i=0)}$$
   
3. **No Anticipation**: Before the treatment takes place ($T=0$), the potential outcomes do not depend on the treatment status. 

$$Y_{i,0}(0) = Y_{i,0}(1)$$

## The DID Estimator

- Lets take a second look at the ATT definition:
$$\begin{aligned}
ATT &=E(Y_{i,1}(1)|D=1)-\color{red}{E(Y_{i,1}(0)|D=1)} \\
&=E(Y_{i,1}|D=1)-\color{red}{E(Y_{i,1}(0)|D=1)}
\end{aligned}
$$

- The problem is to estimate the **red** component, to obtain an estimator for the ATT. 

- However, under the PTA and No Anticipation, the observed part can be written as:
$$E(Y_{i,1}(0)|D=1) = E(Y_{i,1}-Y_{i,0}|D=0) + E(Y_{i,0}|D=1)
$$

- Which gives the usual ATT estimator:

$$ATT =\underbrace{E(Y_{i,1} - Y_{i,0}|D=1)}_{\Delta treat} - \underbrace{E(Y_{i,1}-Y_{i,0}|D=0)}_{\Delta control}$$ 

## Graphically

```{stata}
*| echo: false
*%%set
/*
graph_width = default
graph_height = default
*/
```

```{stata}
*| echo: false
*| fig-align: center

clear
input t d y
0 0 0.5
0 1 0.6
1 0 0.8
1 1 1.1
0 2 0.6
1 2 0.9
end

set scheme white2
color_style s2
two (scatter y t if d==0, connect(l)) ///
	(scatter y t if d==1, connect(l)) ///
	(scatter y t if d==2, connect(l)) ///
	(pci .9 1 1.1 1, lw(2) color(gs5*.5)), ///
	xscale(range(-.1 1.1)) ///
	legend(order(1 "Control" 2 "Treated" 3 "Counterfactual" 4 "ATT")) ///
    ysize(10) xsize(15)
	
```


## How to estimate it?

- **Difference-in-Means**: 
  
$$\hat ATT=\bar Y^{D=1,T=1} - \bar Y^{D=1,T=0} - [ \bar Y^{D=0,T=1} - \bar Y^{D=0,T=0} ]$$

- **Regression**: 

$$Y_{i,t} = \beta_0 + \beta_1 D_i + \beta_2 t + \beta_3 (D_i \times t) + \epsilon_{i,t}$$

- With Panel Data: **Fixed Effects**
  
$$\begin{aligned}
Y_{i,t} &= \beta_0 + \sum \delta_i  + \beta_2 t + \beta_3 (D_i \times t) + \epsilon_{i,t} \\
\Delta Y_{i} &= \beta_2 + \beta_3 D_i + \epsilon_{i} \text{ for } t=1 \\
\end{aligned}
$$

## Extension: Adding Controls

- The DID estimator presented above relies on Uncondiitonal Parallel Trends. It may work if both control and treated groups are similar in all aspects, except for the treatment. But they may not. 
- In this case, we can add controls to the model, to account for differences in the groups.

$$Y_{i,t} = \beta_0 + \beta_1 D_i + \beta_2 t + \beta_3 (D_i \times t) +  X_{it} \gamma + \epsilon_{i,t}$$

- But this would be wrong. Why?

## Problems of Adding Controls

- Simply adding controls imposes assumption of homogenous treatement effects. As described in @santanna_doubly_2020, $\gamma$ may not be the same as the ATT. 
  - Solution: Interactions between controls and all group\\time dummies:
$$y_{i,t} = \beta_0 + \sum \delta_i  + \beta_2 t + \beta_3 (D_i \times t) +  X_{it} \gamma + \sum \gamma_x (X-\bar X_{D\times T})*D*T + \epsilon_{i,t}$$

- Controlling for time varying variables may introduce biases (bad controls)
  - Solution: use only pre-treatment variables as controls. (panel) or variables that should not be affected by the treatment (cross-sections)
  - Also: If using Panel Data, one can add as controls all variables history. (see for example @caetano_difference_2022)

## Potential Solution: @santanna_doubly_2020

- DID is a straighforward estimator, that relies strongly on the Unconditional Parallel Trends Assumption. (UPTA)

- One solution to the problem is to use the **Conditional Parallel Trends Assumption** (CPTA), which can be less restrictive.

- This states that PTA holds, only after conditioning on a set of variables $X$. (looking at subgroups).

$$\color{blue}{E(Y_{i,1}(0) - Y_{i,0}(0)|D_i=1,X)} = \color{green}{E(Y_{i,1}(0)-Y_{i,0}(0)|D_i=0,X)}$$

- So, if you can "control" for individual characteristics, you could estimate the treatment effect, and still report Average Treatment Effects for the population.

$$ATT = E\big[ [E(Y_{i,1}(0) - Y_{i,0}(0)|D_i=1,X ] \big]$$

## Added Assumption

- When accouting for covariates, one needs to add an additional assumption to the data:

- There is an overlap in the distribution of $X$ between the treated and control groups. (common support)

$$0 << Pr(D=1|X) << 1$$

- This is important, because if there is no overlap, the treatment effect cannot be identified for all groups, and may create distorted estimates.

## Potential Solution: `drdid`, `teffects` 

- @santanna_doubly_2020 propose various alternatives to estimate the treatment effect with controls, under CPTA. They contrast the implementation of methods that mix linear regressions, Inverse Probability Weighting (IPW) and Doubly Robust Estimators (DR).
- Similar estimates could be obtained using `teffects` in Stata.
- But how does this work? Two Cases: 
  - Panel Data: This simplifies the problem, because we can use the Data structure to estimate the model.
  - Crossection: This is more complicated because requires careful consideration of idenfication assumptions, and groups of interest.

## Panel Data 

- Step 1: Estimate the changes in the outcome $\Delta Y_i = Y_{i,1} - Y_{i,0}$. (the First D)
  - Because of this, we are implicitly reducing our sample size: from $N$ to $N/2$ (because of the unestimated fixed effects)
- Step 2: Estimate the treatment effect:
  - Simplest case, no controls:
$$\Delta Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i$$ 
  
- In other words, because we have simplified the problem, the model is now a simple linear regression, with 1 period.

## Panel Data: Adding controls

- Because you have now only 1 period, and two groups. All treatment effect estimators can be used.
  - regression outcome, IPW, doubly robust, matching, etc.
  - We use them to estimate the second D of DID
- With Transformed data ($\Delta y$) as dependent variable, any of the methods in `teffects` can be used to estimate the treatment effect, and their Standard errors

- With untransformed data, you can use `drdid` to estimate the treatment effect, and their Standard errors.
    - You need to make sure you have only 2 periods of data.


## Panel Data: Methods

- **Regression**: reg (`drdid`) or ra (`teffects`) 
    - using $\Delta y$ as dependent variable, estimate a linear model with covariates (No FE) for the untreated, and predict outcomes. This would become your "Potential outcome change under no-treatment"
  
$$ ATT = E(\Delta Y_{i}|D=1) - E({\hat\gamma X|D=1})$$

- **Inverse Probability Weighting**: stdipw (`drdid`) or ipw (`teffects`)
    - Estimate the likelihood of being treated, and use it to identify a propensity score and IPW weights $p(D=1|X) = \hat p(X)$
  
$$ ATT = E(\Delta Y_{i}|D=1) - E\left({\Delta Y_{i} \frac{p(X)}{1-p(X)}|D=0}\right)$$

## Panel Data: Methods

- **Doubly Robust Estimation**: dript and dripw (`drdid`) or ipwra aipw (`teffects`)
    - Estimate the likelihood of being treated, and use it to identify a propensity score and IPW weights $p(D=1|X) = \hat p(X)$
    - Estimate a weighted regression with $\Delta y$ as dependent variable or estimate a weighted regression correction. (see [here](https://friosavila.github.io/app_metrics/app_metrics2.html) slide 17-18) for more details.
    - Combinations of modeling outcome and modeling likelihood and pscores makes the estimator doubly robust.

- For Repeated crossection, the math becomes more complicated to follow and identify the "group of interest"  
- See [here](https://friosavila.github.io/app_metrics/app_metrics2.html) slide 53-54 for more details.
  
## Example {.scrollable}

Some Data Preparation

```{stata}
*| classes: larger
*| echo: true
*| code-fold: false
qui:frause lalonde, clear
keep  if treated==0 | sample==2
bysort id (year):gen dy = re[2]-re[1]
```

Using `teffects`:

```{stata}
*| classes: larger
*| echo: true
*| code-fold: false

teffects ra (dy educ black married nodegree hisp re74) (experimental) if year==1975 , atet
```

Using `drdid`:

```{stata}
*| classes: larger
*| echo: true
*| code-fold: false
 
drdid re educ black married nodegree hisp re74 , ivar(id) time(year) tr(experimental) reg
```

by hand:

```{stata}
*| classes: larger
*| echo: true
*| code-fold: false
qui:reg dy educ black married nodegree hisp re74 if exper==0
predict dy_hat, xb
gen att_i = dy-dy_hat
tabstat att_i, by(exper) 
```

## Highlights

- The identification relies on the non-anticipation assumpiton and the parallel trends assumption.
  - Neither of these assumptions can be tested, but they can be supported by the data.
- For Implementation, If one has panel data, `teffects` and `drdid` can be used to estimate the treatment effect, and their standard errors. (after preparing the data)
- Otherwise, `drdid` can be used for repeated crossection as well.

## Highlighs II

- The **overlapping** assumption is important, and has different implications for the different methods.
- When the estimation method is `reg` or `ra`, the overlapping assumption may be less important, because the model is extrapolates to created "potential outcomes" for the treated group.
  - However, extrapolation may not be accurate, or create incorrect extrapolations (base category dummies)
- With doubly robust methods, the overlapping assumption is more relevant. `dript` is particularly sensitive to this assumption, and may not even converge if there is weak overlap.
- For most practical purposes, `dripw` may be the most stable, and preferred method.

## Highlighs III

- With panel data, `drdid` automatically constrains model specification to use pre-treatment information only.
- With Repeated crossection, `drdid` would use both pre-treatment and post-treatment information.
  
# From 2x2 to GxT DID

## How GxT DID was suppoused to work

Incorrect Generalized 2x2 DID. TWFE (adding time and group fixed effects)

and adding Controls

When it works...When it doesnt?
- Homgenous vs heterogenous Treatment effects.

## Why it doesnt work ? 

Negative Weights. Simple Explanation

Incorrect controls: Using Treated and as controls

# Solutions

## General Overview

The root of the problem: Using incorrect control units, because of homogeneity assumption

Solutions: 
- Avoid using controls
- Add Heterogeneity in the treatment effects
- Use Only Good DID designs.

## Avoid using controls: `did_imputation` and `did2s`
#### @borusyak2023revisiting and @gardner2022twostage

## Allowing for Heterogeneity: `jwdid` and `eventstudyinteract`
#### @wooldridge_2021 and @sun_estimating_2021

## Using Good DID Designs: `csdid` and `csdid2`
#### @callaway_2021

## Map: How they Relate








## Suggested readings

::: {#refs}
::: 

